"""
export_handler.py — Clean PDF, Word DOCX, and Markdown export generators for Media Summaries.
"""

from __future__ import annotations
import io
import re
from typing import Any, Dict

# ReportLab imports for PDF generation
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_JUSTIFY

# Python-docx imports for Word document generation
from docx import Document
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_TABLE_ALIGNMENT


import os
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont

_PDF_FONT = "Helvetica"
_PDF_FONT_BOLD = "Helvetica-Bold"

for _fpath in [
    "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
    "/usr/share/fonts/truetype/freefont/FreeSans.ttf",
    "C:\\Windows\\Fonts\\arial.ttf",
    "C:\\Windows\\Fonts\\segoeui.ttf",
]:
    if os.path.exists(_fpath):
        try:
            pdfmetrics.registerFont(TTFont("AppUnicodeFont", _fpath))
            _PDF_FONT = "AppUnicodeFont"
            _PDF_FONT_BOLD = "AppUnicodeFont"
            break
        except Exception:
            pass


def clean_markdown_formatting(text: str) -> str:
    """Removes or converts raw markdown tags for PDF paragraph rendering."""
    if not text:
        return ""
    # Convert bold **text** -> <b>text</b>
    t = re.sub(r'\*\*(.*?)\*\*', r'<b>\1</b>', text)
    # Convert italic *text* -> <i>text</i>
    t = re.sub(r'\*(.*?)\*', r'<i>\1</i>', t)
    # Convert code `text` -> <font name="Courier">\1</font>
    t = re.sub(r'`(.*?)`', r'<font name="Courier" color="#63B3ED">\1</font>', t)
    return t


def generate_pdf_bytes(title: str, summary_text: str, metadata: Dict[str, Any] | None = None) -> bytes:
    """
    Generates a beautifully styled, professional PDF document from summary markdown.

    Returns:
        bytes: The binary PDF data ready for Streamlit download button.
    """
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        rightMargin=40,
        leftMargin=40,
        topMargin=40,
        bottomMargin=40,
    )

    styles = getSampleStyleSheet()

    # Custom styles
    title_style = ParagraphStyle(
        'DocTitle',
        parent=styles['Normal'],
        fontName=_PDF_FONT_BOLD,
        fontSize=20,
        leading=24,
        textColor=colors.HexColor('#1A202C'),
        alignment=TA_LEFT,
        spaceAfter=6,
    )
    subtitle_style = ParagraphStyle(
        'DocSubTitle',
        parent=styles['Normal'],
        fontName=_PDF_FONT,
        fontSize=10,
        leading=14,
        textColor=colors.HexColor('#718096'),
        spaceAfter=12,
    )
    h1_style = ParagraphStyle(
        'Heading1_Custom',
        parent=styles['Normal'],
        fontName=_PDF_FONT_BOLD,
        fontSize=14,
        leading=18,
        textColor=colors.HexColor('#2B6CB0'),
        spaceBefore=14,
        spaceAfter=6,
    )
    h2_style = ParagraphStyle(
        'Heading2_Custom',
        parent=styles['Normal'],
        fontName=_PDF_FONT_BOLD,
        fontSize=12,
        leading=16,
        textColor=colors.HexColor('#2D3748'),
        spaceBefore=10,
        spaceAfter=4,
    )
    body_style = ParagraphStyle(
        'Body_Custom',
        parent=styles['Normal'],
        fontName=_PDF_FONT,
        fontSize=10,
        leading=14,
        textColor=colors.HexColor('#2D3748'),
        alignment=TA_LEFT,
        spaceAfter=6,
    )
    bullet_style = ParagraphStyle(
        'Bullet_Custom',
        parent=styles['Normal'],
        fontName=_PDF_FONT,
        fontSize=10,
        leading=14,
        textColor=colors.HexColor('#2D3748'),
        leftIndent=15,
        spaceAfter=4,
    )


    story = []

    # Title & Header Banner
    story.append(Paragraph(clean_markdown_formatting(title or "Multimodal AI Summary"), title_style))
    meta_str = "Generated by AI Media Summarizer"
    if metadata:
        parts = []
        if metadata.get("duration"):
            parts.append(f"Duration: {metadata['duration']}")
        if metadata.get("language"):
            parts.append(f"Language: {metadata['language']}")
        if parts:
            meta_str += " · " + " | ".join(parts)
    story.append(Paragraph(meta_str, subtitle_style))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#CBD5E0"), spaceAfter=14))

    # Process summary lines into PDF flowables
    lines = summary_text.splitlines()
    for line in lines:
        s_line = line.strip()
        if not s_line:
            story.append(Spacer(1, 4))
            continue

        if s_line.startswith("# "):
            story.append(Paragraph(clean_markdown_formatting(s_line[2:]), h1_style))
        elif s_line.startswith("## "):
            story.append(Paragraph(clean_markdown_formatting(s_line[3:]), h1_style))
        elif s_line.startswith("### "):
            story.append(Paragraph(clean_markdown_formatting(s_line[4:]), h2_style))
        elif s_line.startswith("- ") or s_line.startswith("* "):
            bullet_txt = f"•  {clean_markdown_formatting(s_line[2:])}"
            story.append(Paragraph(bullet_txt, bullet_style))
        elif re.match(r'^\d+\.\s', s_line):
            num_txt = clean_markdown_formatting(s_line)
            story.append(Paragraph(num_txt, bullet_style))
        else:
            story.append(Paragraph(clean_markdown_formatting(s_line), body_style))

    doc.build(story)
    pdf_data = buffer.getvalue()
    buffer.close()
    return pdf_data


def generate_docx_bytes(title: str, summary_text: str, metadata: Dict[str, Any] | None = None) -> bytes:
    """
    Generates a cleanly formatted Microsoft Word (.docx) document.

    Returns:
        bytes: Binary Word document data ready for Streamlit download button.
    """
    doc = Document()

    # Document Margins
    sections = doc.sections
    for section in sections:
        section.top_margin = Inches(0.75)
        section.bottom_margin = Inches(0.75)
        section.left_margin = Inches(0.75)
        section.right_margin = Inches(0.75)

    # Title
    p_title = doc.add_paragraph()
    run_title = p_title.add_run(title or "Multimodal AI Summary")
    run_title.font.name = 'Calibri'
    run_title.font.size = Pt(22)
    run_title.font.bold = True
    run_title.font.color.rgb = RGBColor(43, 108, 176) # #2B6CB0

    # Subtitle
    p_sub = doc.add_paragraph()
    meta_str = "Generated by AI Media Summarizer"
    if metadata:
        parts = []
        if metadata.get("duration"):
            parts.append(f"Duration: {metadata['duration']}")
        if metadata.get("language"):
            parts.append(f"Language: {metadata['language']}")
        if parts:
            meta_str += " · " + " | ".join(parts)
    run_sub = p_sub.add_run(meta_str)
    run_sub.font.name = 'Calibri'
    run_sub.font.size = Pt(10)
    run_sub.font.italic = True
    run_sub.font.color.rgb = RGBColor(113, 128, 150)

    doc.add_paragraph().paragraph_format.space_after = Pt(6)

    # Process summary lines into Word elements
    lines = summary_text.splitlines()
    for line in lines:
        s_line = line.strip()
        if not s_line:
            continue

        if s_line.startswith("# "):
            h = doc.add_heading(level=1)
            r = h.add_run(re.sub(r'[\*\#]', '', s_line[2:]))
            r.font.name = 'Calibri'
            r.font.color.rgb = RGBColor(43, 108, 176)
        elif s_line.startswith("## "):
            h = doc.add_heading(level=1)
            r = h.add_run(re.sub(r'[\*\#]', '', s_line[3:]))
            r.font.name = 'Calibri'
            r.font.color.rgb = RGBColor(43, 108, 176)
        elif s_line.startswith("### "):
            h = doc.add_heading(level=2)
            r = h.add_run(re.sub(r'[\*\#]', '', s_line[4:]))
            r.font.name = 'Calibri'
            r.font.color.rgb = RGBColor(45, 55, 72)
        elif s_line.startswith("- ") or s_line.startswith("* "):
            p = doc.add_paragraph(style='List Bullet')
            _add_formatted_runs(p, s_line[2:])
        elif re.match(r'^\d+\.\s', s_line):
            p = doc.add_paragraph(style='List Number')
            content = re.sub(r'^\d+\.\s', '', s_line)
            _add_formatted_runs(p, content)
        else:
            p = doc.add_paragraph()
            _add_formatted_runs(p, s_line)

    buffer = io.BytesIO()
    doc.save(buffer)
    docx_data = buffer.getvalue()
    buffer.close()
    return docx_data


def _add_formatted_runs(paragraph: Any, text: str) -> None:
    """Helper to parse markdown **bold** and *italics* into docx runs."""
    tokens = re.split(r'(\*\*.*?\*\*|\*.*?\*|`.*?`)', text)
    for token in tokens:
        if not token:
            continue
        if token.startswith('**') and token.endswith('**'):
            r = paragraph.add_run(token[2:-2])
            r.bold = True
        elif token.startswith('*') and token.endswith('*'):
            r = paragraph.add_run(token[1:-1])
            r.italic = True
        elif token.startswith('`') and token.endswith('`'):
            r = paragraph.add_run(token[1:-1])
            r.font.name = 'Courier New'
            r.font.color.rgb = RGBColor(99, 179, 237)
        else:
            paragraph.add_run(token)
